wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
hl_size:
  value: 64
initialization:
  value: xavier
loss_type:
  value: cross_entropy
lr:
  value: 1.0e-05
n_epoch:
  value: 3
n_hiddenlayer:
  value: 3
optimizer:
  value: adam
reg:
  value: 0
